@api_HostAddress=http://localhost:4173/api
@web_HostAddress=http://localhost:4173

#
# API
#

###
GET {{api_HostAddress}}/weatherforecast

###
GET {{api_HostAddress}}/health

#
# WEB
#

###
GET {{web_HostAddress}}/config.js

###
GET {{web_HostAddress}}/health
