name: Docker-IRL-Demo

services:
  api:
    build:
      context: ./api
      target: final
    container_name: api
    environment:
      AppPathBase: /api

  web:
    build:
      context: ./web
    container_name: web
    environment:
      API_VIRTUAL_NAME: api
      API_HOST: api
      API_INTERNAL_PORT: 8080
    ports:
      - '127.0.0.1:4173:80'
