name: Docker-IRL-Demo

services:

  db:
    image: mcr.microsoft.com/mssql/server:2022-CU18-ubuntu-22.04@sha256:ea73825f3d88a23c355ac2f9fdc6bd960fec90171c12c572109b36a558f77bb8
    container_name: mssql
    volumes:
      - weather-mssql-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - '127.0.0.1:1435:1433'
    healthcheck:
      test: ${MSSQL_HEALTH_CHECK}
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  api:
    build:
      context: ./api
      target: final
    container_name: api
    environment:
      AppPathBase: /api
      ConnectionStrings__DefaultConnection: ${MSSQL_CONNECTION_STRING}
    depends_on:
      - db

  web:
    build:
      context: ./web
    container_name: web
    environment:
      API_VIRTUAL_NAME: api
      API_HOST: api
      API_INTERNAL_PORT: 8080
    ports:
      - '127.0.0.1:4173:80'
    depends_on:
      - api

volumes:
  weather-mssql-data:
